### ISSUE TITLE
R2 produces extra curly brackets in a certain situation

### ISSUE THREAD

**Issue by idosius** [ded/R2#20]
The following code:

``` css
.flex-caption { zoom: 1;}
.flex-caption {}
.flex-direction-nav li a {
color: black;
}
```

Produces the following result via R2 (notice the double curly brackets in the beginning):

``` css
.flex-caption{zoom:1;}}.flex-direction-nav li a{color:black;}
```
