### ISSUE TITLE
Media queries and asterisks

### ISSUE THREAD

**Issue by ma7moudat** [ded/R2#21]
It appears that the following rules are not swapped properly:
1. Rules preceded by an asterisk (*)
2. The FIRST rule of the FIRST selector inside a media query (@media)

Please check the (not swapped) lines below

``` css
.style1 {
    margin-left: 20px;
    *margin-left: 20px; /* not swapped */
}
@media ... {
    .style1 {
        margin-left: 20px; /* not swapped */
        margin-left: 20px;
    }
    .style2 {
        margin-left: 20px;
    }
}
```
