### ISSUE TITLE
Semicolons in content block can break parsing

### ISSUE THREAD

**Issue by dustinsmith1024** [ded/R2#8]
Our css had a semicolon inside a content block and it appears to break the parsing.  Assuming we would have to do some checking before the declarations.split call to catch it.  I removed the semi-colon for now and it goes on.

``` css
b.broke:before {
  content:"&darr;";
}
```

gets parsed like so:

``` css
b.broke:before{content:"&darr;}
```
